# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_programm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.XML_menu = QtWidgets.QWidget()
        self.XML_menu.setObjectName("XML_menu")
        self.xml_logo = QtWidgets.QLabel(self.XML_menu)
        self.xml_logo.setGeometry(QtCore.QRect(510, 0, 120, 120))
        self.xml_logo.setText("")
        self.xml_logo.setPixmap(QtGui.QPixmap("Qtdesigner\XML_LOGO.jpg"))
        self.xml_logo.setScaledContents(True)
        self.xml_logo.setWordWrap(False)
        self.xml_logo.setObjectName("xml_logo")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.XML_menu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 511, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.open_button.setObjectName("open_button")
        self.verticalLayout.addWidget(self.open_button)
        self.parsing_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.parsing_button.setObjectName("parsing_button")
        self.verticalLayout.addWidget(self.parsing_button)
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.text_info_xml = QtWidgets.QPlainTextEdit(self.XML_menu)
        self.text_info_xml.setGeometry(QtCore.QRect(0, 125, 640, 300))
        self.text_info_xml.setObjectName("text_info_xml")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.XML_menu)
        self.verticalScrollBar.setGeometry(QtCore.QRect(615, 126, 20, 297))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tabWidget.addTab(self.XML_menu, "")
        self.Excel = QtWidgets.QWidget()
        self.Excel.setObjectName("Excel")
        self.excel_logo = QtWidgets.QLabel(self.Excel)
        self.excel_logo.setGeometry(QtCore.QRect(510, 0, 120, 120))
        self.excel_logo.setText("")
        self.excel_logo.setPixmap(QtGui.QPixmap("Qtdesigner\EXCEL_LOGO.png"))
        self.excel_logo.setScaledContents(True)
        self.excel_logo.setObjectName("excel_logo")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Excel)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 511, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.open_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.open_button_2.setObjectName("open_button_2")
        self.verticalLayout_2.addWidget(self.open_button_2)
        self.parsing_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.parsing_button_2.setObjectName("parsing_button_2")
        self.verticalLayout_2.addWidget(self.parsing_button_2)
        self.save_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.save_button_2.setObjectName("save_button_2")
        self.verticalLayout_2.addWidget(self.save_button_2)
        self.text_info_xml_2 = QtWidgets.QPlainTextEdit(self.Excel)
        self.text_info_xml_2.setGeometry(QtCore.QRect(0, 125, 640, 300))
        self.text_info_xml_2.setObjectName("text_info_xml_2")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.Excel)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(615, 126, 20, 297))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.tabWidget.addTab(self.Excel, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_button.setText(_translate("MainWindow", "Открыть "))
        self.parsing_button.setText(_translate("MainWindow", "Поиск цен"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.XML_menu), _translate("MainWindow", "XML файл"))
        self.open_button_2.setText(_translate("MainWindow", "Открыть "))
        self.parsing_button_2.setText(_translate("MainWindow", "Поиск цен"))
        self.save_button_2.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Excel), _translate("MainWindow", "Excel файл"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
